# Generated by Django 3.0.1 on 2019-12-31 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20191231_0828'),
        ('mcq', '0002_mcqqattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.MCQ')),
                ('quiz_attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizAttempt')),
            ],
        ),
        migrations.DeleteModel(
            name='MCQQAttempt',
        ),
    ]
